class Emoji:
    ALIVE               = "🙂"
    DEAD                = "💀"
    FIRST_DEATH         = "🩸"
    SPEEDY_GONZALES     = "🏃‍♂️"
    ZONA_CESARINI       = "⛄️"
    CLUB_27             = "🤟"
    HAPPY_BIRTHDAY      = "🎂"
    CAPTAIN             = "©️"
    GLOBETROTTER        = "🌍"
    INCLUSIVITY         = "🏳️‍🌈"
    JACK_OF_ALL_TRADES  = "💼"
    FIRST_PLACE         = "🏆"
    SECOND_PLACE        = "🥈"
    THIRD_PLACE         = "🥉"